services:
  kdo-vtg:
    build: .
    container_name: kdo-vtg
    volumes:
      - ./videos:/videos:ro
      - ./output:/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
