services:
  kdo-vtg:
    build: .
    container_name: kdo-vtg
    ports:
      - "8080:8000"
    volumes:
      - ./config:/app/config:rw
      - /path/to/videos:/media:ro
    environment:
      - TZ=Europe/Bucharest
      - PUID=1000
      - PGID=100
    restart: unless-stopped
